# Generated by Django 2.0.7 on 2018-07-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('booking_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.AvailableTime')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=50)),
                ('category', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.Type'),
        ),
    ]
