# Generated by Django 2.0.7 on 2018-08-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='duration_in_min',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='type',
            name='price',
            field=models.FloatField(default=20),
        ),
    ]
