# Generated by Django 2.0.7 on 2018-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20180801_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='details',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
